### ISSUE TITLE
Is there any possibily to list all created jobs?

### ISSUE THREAD

**Issue by Starwhooper** [Martin-Laclaustra/CronAlarms#26]

**Comment by Martin-Laclaustra** [comment]
This library works with a closed list of possible alarms (jobs).
https://github.com/Martin-Laclaustra/CronAlarms/blob/3ad9ac8507a07c85c03a0ef58f46897e02b80d0d/src/CronAlarms.h#L15

You can just iterate across the list and check which ones are enabled (allocated), like it is done while "servicing".
https://github.com/Martin-Laclaustra/CronAlarms/blob/3ad9ac8507a07c85c03a0ef58f46897e02b80d0d/src/CronAlarms.cpp#L188

**Comment by Starwhooper** [comment]
Thank you,
with this code, i get the next start for each job:
```
  for (byte i = 0; i < Cron.count(); i++){
    time_t now = Cron.getNextTrigger(i);
    char buffer[19];
    strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", localtime(&now));
    Serial.println(buffer);
  }
```
But how can i get which function will be triggert ?

**Comment by Martin-Laclaustra** [comment]
I have not tested this code but this should tell which is the id of the next alarm:

```
uint8_t CronClass::getNextTriggerId() const
{
  time_t nextTrigger = 0;
  uint8_t nextId = 0;

  for (uint8_t id = 0; id < dtNBR_ALARMS; id++) {
    if (isAllocated(id)) {
      if (nextTrigger == 0) {
        nextTrigger = Alarm[id].nextTrigger;
        nextId = id;
      }
      else if (Alarm[id].nextTrigger <  nextTrigger) {
        nextTrigger = Alarm[id].nextTrigger;
        nextId = id;
      }
    }
  }
  return nextId;
}
```

**Comment by Starwhooper** [comment]
Hello @Martin-Laclaustra,

thank you very much for the quick answer.
Unfortunately, I seem to have expressed my question incorrectly.

Hence a fictitious example:
I have created a cron job that is supposed to execute the lunchtime function every day at 12:00 p.m.
I have now learned from you how I can list all the jobs that have been set up and read out the time. In your example you also explain how I can read the ID for the next job.
But what I'm still looking for is a way to read out not the ID and not the time, but the command to be triggered.

So in something like this:
```
char nameofcommandtoexecute = Cron.getTriggerCommand(i)
serial.print(‘will do as next: ’ + String(nameofcommandtoexecute))
```

Regards, Thiemo

**Comment by Martin-Laclaustra** [comment]
There is no string stored when you assign a job:
https://github.com/Martin-Laclaustra/CronAlarms/blob/3ad9ac8507a07c85c03a0ef58f46897e02b80d0d/examples/CronAlarms_example/CronAlarms_example.ino#L53

Your only option is to create and maintain a table in your code, storing the appropriate string every time you create a job, and store the assigned id, which you can obtain like in:
https://github.com/Martin-Laclaustra/CronAlarms/blob/3ad9ac8507a07c85c03a0ef58f46897e02b80d0d/examples/CronAlarms_example/CronAlarms_example.ino#L59

Then, you can compare the next id with that lookup table and print out whatever info you recorded.
