### ISSUE TITLE
Problem using OnTick_t

### ISSUE THREAD

**Issue by XeoSmartHome** [Martin-Laclaustra/CronAlarms#4]
`virtual void onScheduleUpdate(JsonDocument& actions) override{
		JsonArray actions_array = actions.as<JsonArray>();

		for (JsonVariant action : actions_array) {
			const char* action_name = action["name"];

			if (strcmp(action_name, "irigate") == 0) {
				const char* cron = action["cron"];

				OnTick_t tic = [this]() { // no suitable conversion function from to exists from lamda [] void () to OnTick_t 
					MyDevice::irigate(this, 3, 4);
				};

				Cron.create(cron, tic, false);

			}

		}
	}`

**Comment by Martin-Laclaustra** [comment]
You will need a pointer to a static function in order to set the callback.
That is all I can say given that you do not provide any context at all.

**Comment by XeoSmartHome** [comment]
.
