### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by ghost** [Martin-Laclaustra/CronAlarms#5]
Hello do you have contact details anywhere like email or twitter?

thanks

**Comment by Martin-Laclaustra** [comment]
Please, if you express the reason why you need an additional communication channel (beyond this) we could find a way. I could reach you.

**Comment by ghost** [comment]
I saw your interest in video on esp32 and I was curious to know if you had seen this: 

https://www.reddit.com/r/esp32/comments/gosbxg/esp_8_bit_atari_8_bit_computers_nes_and_sms_game/

The interesting thing being that it displays NTSC as well as PAL on composite video from esp32.  NTSC has never been done before successfully.

**Comment by Martin-Laclaustra** [comment]
My code works fine in NTSC. Please have a look at my fork of ESP32lib.

**Comment by ghost** [comment]
Do you also use the audio PLL to achieve NTSC, like esp_8_bit?  What does your solution do different to ESP32lib to get NTSC?  esp_8_bit also says it has very stable color PAL signal due to the audio PLL - curious to know if your code does this too?

I'm hoping there will be NTSC and Pal for FabGL one day because there a well documented development libraries and also the VT100 terminal on FabGL.  At the moment it is only VGA.

http://www.fabglib.org/classfabgl_1_1_canvas.html

Maybe one day the various solutions will merge in some way so all the best features of each are combined,

**Comment by Martin-Laclaustra** [comment]
I am working in a highly portable code. Still not ready.
Current public version ("advanced" branch):
NTSC works very well (slow, but new upcoming version is fast and allows millions of colors). PAL needs more work. I will need to study what esp_8_bit does. For now, bitluni's lib with my extension is the only library capable of outputing to both VGA and composite. I you want details you can read the issues in bitluni's repo and see the changes I did in the commits (my commit comments aim to be self-explanatory and the diffs are incremental to be easy to understand).
Do you have specific suggestions? are you willing to help and get involved in the development?

**Comment by ghost** [comment]
Mainly I'm interested because I'd like to write applications that can be displayed on analog TVs.  For some reason I have collected about 20 old analog TVs (alongside a large vintage computer collection).

>>Do you have specific suggestions? 

No, mostly I'm just curious about how and why the various solutions do things as they do.  I just find video/VGA/PAL/NTSC on esp32 an interesting field. There's lots of great innovation - all the libraries seem unique in some way and each discover new and amazing ways to do things.

I made a comparison of each:
https://www.reddit.com/r/esp32/comments/gpezk3/feature_comparison_of_esp32_graphics_sound_game/

**Comment by ghost** [comment]
>> upcoming version is fast and allows millions of colors

I'm keen to do testing. I have TV's capable of NTSC and PAL.

Have you thought about trying it on the esp32-s2? The possible advantage there is that more PSRAM can be mapped into DMA addressable space which perhaps could make a larger frame buffer.

Do you have a repo with your new driver in it yet?

**Comment by Martin-Laclaustra** [comment]
Your help is welcome. Please refer to https://github.com/bitluni/ESP32Lib/issues/50#issue-618742128 where you will find all the information on the development.
I do not have any esp32-s2. Have you tried bitluni's lib vga in it? You can try mine for composite (it is the same lib). I do not know how advanced the support for it in the arduino-esp32 project is. ... nor how different the registers to control I2S are. However, I have other ports in mind for the code first, but they will have to wait for now.
I am closing this issue here as this is totally unrelated to CronAlarms.
