### ISSUE TITLE
arduino mkr

### ISSUE THREAD

**Issue by ceceghini** [Martin-Laclaustra/CronAlarms#7]
Not work with arduino mkr. Are there some configuration problem?

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.

**Comment by Martin-Laclaustra** [comment]
Sorry but you need to provide details in order to find a potential bug.
Please read:
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

I am closing the issue. Feel free to reopen it with relevant information.
Best.
