### ISSUE TITLE
Cronjob never starts

### ISSUE THREAD

**Issue by th3-sh0w3r** [Martin-Laclaustra/CronAlarms#9]
This is my code, it's not in an ino file it's in its own class.
The init is called correctly and "Cron set" is shown in console but after that nothing works. Loop is also running (checked with println)

```
void TIMER::init()
{
  struct tm tm_newtime; // set time to Saturday 8:29:00am Jan 1 2011
  tm_newtime.tm_year = 2011 - 1900;
  tm_newtime.tm_mon = 1 - 1;
  tm_newtime.tm_mday = 1;
  tm_newtime.tm_hour = 8;
  tm_newtime.tm_min = 29;
  tm_newtime.tm_sec = 0;
  tm_newtime.tm_isdst = 0;
  timeval tv = { mktime(&tm_newtime), 0 };
  settimeofday(&tv, nullptr);

  Cron.create("*/15 * * * * *", this->timedFunction, false);

  Serial.println("Cron set!");
}

void TIMER::loop()
{
  Cron.delay();
  yield();
}

void TIMER::timedFunction()
{
  Serial.println("Cron called!");
}
```

**Comment by th3-sh0w3r** [comment]
Could fix this. Somehow my loop got deleted after created a freeRTOS task pinned to core

**Comment by th3-sh0w3r** [comment]
Another question: is there a way to overgive arguments to the called function?

**Comment by Martin-Laclaustra** [comment]
You could create member variables in your class that can be accessed from the called function.
Changing the called function signature would require changes to the library code.
